//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoLotEntities : DbContext
    {
        public AutoLotEntities()
            : base("AutoLotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessCustomers> BusinessCustomers { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<PrivateCustomers> PrivateCustomers { get; set; }
        public virtual DbSet<SalesContracts> SalesContracts { get; set; }
        public virtual DbSet<Trucks> Trucks { get; set; }
        public virtual DbSet<LeasingContracts> LeasingContracts { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
