//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesContracts
    {
        public int SalesID { get; set; }
        public string Customer { get; set; }
        public string Car { get; set; }
        public int Price { get; set; }
        public System.DateTime DateOfSale { get; set; }
    }
}
