//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2.ADO.Net_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarID { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
