//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2.ADO.Net_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateCustomers
    {
        public int CustomerID { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public string Name { get; set; }
        public System.DateTime Age { get; set; }
        public string Sex { get; set; }
        public bool NewsReciever { get; set; }
    }
}
