//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPrivate
    {
        public CustomerPrivate()
        {
            this.ContractSales = new HashSet<ContractSale>();
        }
    
        public int CustomerPrivateID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public bool NewsReciever { get; set; }
        public System.DateTime Age { get; set; }
        public string Sex { get; set; }
    
        public virtual ICollection<ContractSale> ContractSales { get; set; }
    }
}
