//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBusiness
    {
        public CustomerBusiness()
        {
            this.ContractLeasings = new HashSet<ContractLeasing>();
        }
    
        public int SENumber { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> Fax { get; set; }
        public bool NewsReciever { get; set; }
    
        public virtual ICollection<ContractLeasing> ContractLeasings { get; set; }
    }
}
