//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCar
    {
        public VehicleCar()
        {
            this.ContractSales = new HashSet<ContractSale>();
        }
    
        public int VehicleCarID { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public int Price { get; set; }
    
        public virtual ICollection<ContractSale> ContractSales { get; set; }
    }
}
