//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTruck
    {
        public VehicleTruck()
        {
            this.ContractLeasings = new HashSet<ContractLeasing>();
        }
    
        public int VehicleTruckID { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public int Price { get; set; }
    
        public virtual ICollection<ContractLeasing> ContractLeasings { get; set; }
    }
}
